<x-app-layout>
    @section('title', 'Tambah Barang')
    <x-slot name="header"><h2 class="font-semibold text-xl text-gray-800 dark:text-gray-200 leading-tight">Tambah Barang</h2></x-slot>
    <div class="max-w-3xl">
        <div class="bg-white dark:bg-gray-800 rounded-xl shadow-sm border border-gray-200 dark:border-gray-700 p-6">
            <form method="POST" action="{{ route('products.store') }}" enctype="multipart/form-data">
                @csrf
                <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div><label for="code" class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">Kode Barang <span class="text-red-500">*</span></label><input type="text" name="code" id="code" value="{{ old('code') }}" class="w-full rounded-lg border-gray-300 dark:border-gray-600 dark:bg-gray-700 dark:text-white focus:ring-red-500 focus:border-red-500" required>@error('code')<p class="mt-1 text-sm text-red-500">{{ $message }}</p>@enderror</div>
                    <div><label for="name" class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">Nama Barang <span class="text-red-500">*</span></label><input type="text" name="name" id="name" value="{{ old('name') }}" class="w-full rounded-lg border-gray-300 dark:border-gray-600 dark:bg-gray-700 dark:text-white focus:ring-red-500 focus:border-red-500" required>@error('name')<p class="mt-1 text-sm text-red-500">{{ $message }}</p>@enderror</div>
                    <div><label for="category_id" class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">Kategori <span class="text-red-500">*</span></label><select name="category_id" id="category_id" class="w-full rounded-lg border-gray-300 dark:border-gray-600 dark:bg-gray-700 dark:text-white focus:ring-red-500 focus:border-red-500" required><option value="">Pilih Kategori</option>@foreach($categories as $cat)<option value="{{ $cat->id }}" {{ old('category_id') == $cat->id ? 'selected' : '' }}>{{ $cat->name }}</option>@endforeach</select>@error('category_id')<p class="mt-1 text-sm text-red-500">{{ $message }}</p>@enderror</div>
                    <div><label for="condition" class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">Kondisi <span class="text-red-500">*</span></label><select name="condition" id="condition" class="w-full rounded-lg border-gray-300 dark:border-gray-600 dark:bg-gray-700 dark:text-white focus:ring-red-500 focus:border-red-500" required>@foreach(['Baik', 'Rusak Ringan', 'Rusak Berat', 'Dalam Perbaikan'] as $cond)<option value="{{ $cond }}" {{ old('condition') == $cond ? 'selected' : '' }}>{{ $cond }}</option>@endforeach</select>@error('condition')<p class="mt-1 text-sm text-red-500">{{ $message }}</p>@enderror</div>
                    <div><label for="stock" class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">Stok <span class="text-red-500">*</span></label><input type="number" name="stock" id="stock" value="{{ old('stock', 0) }}" min="0" class="w-full rounded-lg border-gray-300 dark:border-gray-600 dark:bg-gray-700 dark:text-white focus:ring-red-500 focus:border-red-500" required>@error('stock')<p class="mt-1 text-sm text-red-500">{{ $message }}</p>@enderror</div>
                    <div><label for="minimum_stock" class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">Stok Minimum</label><input type="number" name="minimum_stock" id="minimum_stock" value="{{ old('minimum_stock', 0) }}" min="0" class="w-full rounded-lg border-gray-300 dark:border-gray-600 dark:bg-gray-700 dark:text-white focus:ring-red-500 focus:border-red-500">@error('minimum_stock')<p class="mt-1 text-sm text-red-500">{{ $message }}</p>@enderror</div>
                    <div class="md:col-span-2"><label for="storage_location" class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">Lokasi Penyimpanan <span class="text-red-500">*</span></label><input type="text" name="storage_location" id="storage_location" value="{{ old('storage_location') }}" class="w-full rounded-lg border-gray-300 dark:border-gray-600 dark:bg-gray-700 dark:text-white focus:ring-red-500 focus:border-red-500" required>@error('storage_location')<p class="mt-1 text-sm text-red-500">{{ $message }}</p>@enderror</div>
                    <div class="md:col-span-2"><label for="image" class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">Gambar Barang</label><input type="file" name="image" id="image" accept="image/*" class="w-full text-sm text-gray-500 dark:text-gray-400 file:mr-4 file:py-2 file:px-4 file:rounded-lg file:border-0 file:text-sm file:font-medium file:bg-red-50 file:text-red-700 hover:file:bg-red-100 dark:file:bg-red-900 dark:file:text-red-300">@error('image')<p class="mt-1 text-sm text-red-500">{{ $message }}</p>@enderror</div>
                </div>
                <div class="mt-6 flex items-center gap-3">
                    <button type="submit" class="px-6 py-2.5 bg-red-600 hover:bg-red-700 text-white text-sm font-medium rounded-lg transition-colors">Simpan</button>
                    <a href="{{ route('products.index') }}" class="px-6 py-2.5 bg-gray-100 dark:bg-gray-700 text-gray-700 dark:text-gray-300 text-sm font-medium rounded-lg hover:bg-gray-200 dark:hover:bg-gray-600 transition-colors">Batal</a>
                </div>
            </form>
        </div>
    </div>
</x-app-layout>
